-type(net()::{[atom()], dict()} | {[{atom(), atom()}], dict()}).
-define(NOISE_AVG, -75.0).
-define(NOISE_DELTA, 5.0).
-define(SENSITIVITY, 4.0).
-define(NODENAME, "eliot").
-define(INTERFACE, "en0").
